[project]
requires-python = ">=3.10"
name = "uno-discord"
version = "1.0"
dependencies = ["discord", "dotenv"]

[tool.setuptools]
packages = ["controllers", "models", "UI", "utils", "repos", "services"]
py-modules = ["__init__"]
